# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7731e76d542c8dd476f0be437ae5728856d3ff323fbfc486c8f43f2d53bfe3c7cc035cabe61a9b92b3ea2dc6a2248fcaf918e932b4997c8ad7895984476caf18

test:
  secret_key_base: ce0d4cef1d2d13514c3cf4a3cea9b36fc418b4ea238cfbe036d713f9bb282f59ff25c8cdfe3cf65d556a730981eebe1feeb11d8bb7586e907ab0f093a85d153a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
